# Generated by Django 4.1.6 on 2023-02-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=200)),
                ('mbrd', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('cdr', models.BooleanField()),
                ('gpu', models.CharField(max_length=200)),
                ('sbrd', models.CharField(max_length=200)),
                ('psu', models.CharField(max_length=200)),
                ('ncu', models.CharField(max_length=200)),
                ('isOn', models.BooleanField()),
                ('classR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compView.classroom')),
            ],
        ),
    ]
