# Generated by Django 4.1.6 on 2023-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='number',
        ),
        migrations.AddField(
            model_name='classroom',
            name='room',
            field=models.CharField(default='sala', max_length=200),
        ),
        migrations.AddField(
            model_name='computer',
            name='drive',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='computer',
            name='gpu',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='computer',
            name='mbrd',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ncu',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='computer',
            name='num',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='computer',
            name='psu',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='computer',
            name='sbrd',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
