# Generated by Django 4.1.6 on 2023-02-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compView', '0002_remove_classroom_number_classroom_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='drive',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='gpu',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='mbrd',
            new_name='sys',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='cdr',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='ncu',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='num',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='psu',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='sbrd',
        ),
    ]
